<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Kampus;

class KampusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kampuses = [
            // Top Universities in Indonesia
            [
                'kode_pt' => 'UNV001',
                'nama_kampus' => 'Universitas Indonesia',
                'alamat' => 'Jl. Margonda Raya, Depok',
                'kota' => 'Depok',
                'provinsi' => 'Jawa Barat',
                'telepon' => '021-7863479',
                'email' => 'info@ui.ac.id',
                'website' => 'https://www.ui.ac.id',
            ],
            [
                'kode_pt' => 'UNV002',
                'nama_kampus' => 'Institut Teknologi Bandung',
                'alamat' => 'Jl. Ganesha No. 10, Bandung',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'telepon' => '022-2500935',
                'email' => 'info@itb.ac.id',
                'website' => 'https://www.itb.ac.id',
            ],
            [
                'kode_pt' => 'UNV003',
                'nama_kampus' => 'Universitas Gadjah Mada',
                'alamat' => 'Bulaksumur, Yogyakarta',
                'kota' => 'Yogyakarta',
                'provinsi' => 'D.I. Yogyakarta',
                'telepon' => '0274-588688',
                'email' => 'info@ugm.ac.id',
                'website' => 'https://www.ugm.ac.id',
            ],
            [
                'kode_pt' => 'UNV004',
                'nama_kampus' => 'Institut Teknologi Sepuluh Nopember',
                'alamat' => 'Jl. Raya ITS, Surabaya',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'telepon' => '031-5947274',
                'email' => 'info@its.ac.id',
                'website' => 'https://www.its.ac.id',
            ],
            [
                'kode_pt' => 'UNV005',
                'nama_kampus' => 'Universitas Brawijaya',
                'alamat' => 'Jl. Veteran, Malang',
                'kota' => 'Malang',
                'provinsi' => 'Jawa Timur',
                'telepon' => '0341-575777',
                'email' => 'info@ub.ac.id',
                'website' => 'https://www.ub.ac.id',
            ],
            [
                'kode_pt' => 'UNV006',
                'nama_kampus' => 'Universitas Airlangga',
                'alamat' => 'Jl. Dharmawangsa Dalam Selatan, Surabaya',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'telepon' => '031-5030252',
                'email' => 'info@unair.ac.id',
                'website' => 'https://www.unair.ac.id',
            ],
            [
                'kode_pt' => 'UNV007',
                'nama_kampus' => 'Universitas Padjadjaran',
                'alamat' => 'Jl. Raya Bandung-Sumedang KM 21, Jatinangor',
                'kota' => 'Sumedang',
                'provinsi' => 'Jawa Barat',
                'telepon' => '022-7796200',
                'email' => 'info@unpad.ac.id',
                'website' => 'https://www.unpad.ac.id',
            ],
            [
                'kode_pt' => 'UNV008',
                'nama_kampus' => 'Universitas Diponegoro',
                'alamat' => 'Jl. Prof. Soedarto, SH, Tembalang, Semarang',
                'kota' => 'Semarang',
                'provinsi' => 'Jawa Tengah',
                'telepon' => '024-7460024',
                'email' => 'info@undip.ac.id',
                'website' => 'https://www.undip.ac.id',
            ],
            [
                'kode_pt' => 'UNV009',
                'nama_kampus' => 'Universitas Sebelas Maret',
                'alamat' => 'Jl. Ir. Sutami No. 36A, Solo',
                'kota' => 'Surakarta',
                'provinsi' => 'Jawa Tengah',
                'telepon' => '0271-646994',
                'email' => 'info@uns.ac.id',
                'website' => 'https://www.uns.ac.id',
            ],
            [
                'kode_pt' => 'UNV010',
                'nama_kampus' => 'Universitas Negeri Yogyakarta',
                'alamat' => 'Jl. Colombo No. 1, Yogyakarta',
                'kota' => 'Yogyakarta',
                'provinsi' => 'D.I. Yogyakarta',
                'telepon' => '0274-586168',
                'email' => 'info@uny.ac.id',
                'website' => 'https://www.uny.ac.id',
            ],
            [
                'kode_pt' => 'UNV011',
                'nama_kampus' => 'Universitas Hasanuddin',
                'alamat' => 'Jl. Perintis Kemerdekaan KM 10, Makassar',
                'kota' => 'Makassar',
                'provinsi' => 'Sulawesi Selatan',
                'telepon' => '0411-585024',
                'email' => 'info@unhas.ac.id',
                'website' => 'https://www.unhas.ac.id',
            ],
            [
                'kode_pt' => 'UNV012',
                'nama_kampus' => 'Universitas Andalas',
                'alamat' => 'Jl. Universitas Andalas, Padang',
                'kota' => 'Padang',
                'provinsi' => 'Sumatera Barat',
                'telepon' => '0751-72701',
                'email' => 'info@unand.ac.id',
                'website' => 'https://www.unand.ac.id',
            ],
            [
                'kode_pt' => 'UNV013',
                'nama_kampus' => 'Universitas Sumatera Utara',
                'alamat' => 'Jl. Dr. Mansur No. 9, Medan',
                'kota' => 'Medan',
                'provinsi' => 'Sumatera Utara',
                'telepon' => '061-8213737',
                'email' => 'info@usu.ac.id',
                'website' => 'https://www.usu.ac.id',
            ],
            [
                'kode_pt' => 'UNV014',
                'nama_kampus' => 'Universitas Udayana',
                'alamat' => 'Jl. Raya Kampus UNUD, Denpasar',
                'kota' => 'Denpasar',
                'provinsi' => 'Bali',
                'telepon' => '0361-223797',
                'email' => 'info@unud.ac.id',
                'website' => 'https://www.unud.ac.id',
            ],
            [
                'kode_pt' => 'UNV015',
                'nama_kampus' => 'Universitas Lampung',
                'alamat' => 'Jl. Prof. Dr. Sumantri Brojonegoro No. 1, Bandar Lampung',
                'kota' => 'Bandar Lampung',
                'provinsi' => 'Lampung',
                'telepon' => '0721-705000',
                'email' => 'info@unila.ac.id',
                'website' => 'https://www.unila.ac.id',
            ],
            [
                'kode_pt' => 'UNV016',
                'nama_kampus' => 'Universitas Jember',
                'alamat' => 'Jl. Kalimantan No. 37, Jember',
                'kota' => 'Jember',
                'provinsi' => 'Jawa Timur',
                'telepon' => '0331-330224',
                'email' => 'info@unej.ac.id',
                'website' => 'https://www.unej.ac.id',
            ],
            [
                'kode_pt' => 'UNV017',
                'nama_kampus' => 'Universitas Riau',
                'alamat' => 'Jl. HR. Soebrantas KM 12.5, Pekanbaru',
                'kota' => 'Pekanbaru',
                'provinsi' => 'Riau',
                'telepon' => '0761-63266',
                'email' => 'info@unri.ac.id',
                'website' => 'https://www.unri.ac.id',
            ],
            [
                'kode_pt' => 'UNV018',
                'nama_kampus' => 'Universitas Bengkulu',
                'alamat' => 'Jl. WR. Supratman, Bengkulu',
                'kota' => 'Bengkulu',
                'provinsi' => 'Bengkulu',
                'telepon' => '0736-21170',
                'email' => 'info@unib.ac.id',
                'website' => 'https://www.unib.ac.id',
            ],
            [
                'kode_pt' => 'UNV019',
                'nama_kampus' => 'Universitas Jambi',
                'alamat' => 'Jl. Lintas Jambi-Ma. Bulian KM 15, Jambi',
                'kota' => 'Jambi',
                'provinsi' => 'Jambi',
                'telepon' => '0741-583444',
                'email' => 'info@unja.ac.id',
                'website' => 'https://www.unja.ac.id',
            ],
            [
                'kode_pt' => 'UNV020',
                'nama_kampus' => 'Universitas Palangka Raya',
                'alamat' => 'Jl. Hendrik Timang, Palangka Raya',
                'kota' => 'Palangka Raya',
                'provinsi' => 'Kalimantan Tengah',
                'telepon' => '0536-3226356',
                'email' => 'info@upr.ac.id',
                'website' => 'https://www.upr.ac.id',
            ],
            // Private Universities
            [
                'kode_pt' => 'PTS001',
                'nama_kampus' => 'Universitas Bina Nusantara',
                'alamat' => 'Jl. Kebon Jeruk Raya No. 27, Jakarta',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'telepon' => '021-5345830',
                'email' => 'info@binus.edu',
                'website' => 'https://www.binus.ac.id',
            ],
            [
                'kode_pt' => 'PTS002',
                'nama_kampus' => 'Universitas Trisakti',
                'alamat' => 'Jl. Kyai Tapa No. 1, Jakarta',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'telepon' => '021-5663232',
                'email' => 'info@trisakti.ac.id',
                'website' => 'https://www.trisakti.ac.id',
            ],
            [
                'kode_pt' => 'PTS003',
                'nama_kampus' => 'Universitas Tarumanagara',
                'alamat' => 'Jl. Letjen S. Parman No. 1, Jakarta',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'telepon' => '021-5663124',
                'email' => 'info@untar.ac.id',
                'website' => 'https://www.untar.ac.id',
            ],
            [
                'kode_pt' => 'PTS004',
                'nama_kampus' => 'Universitas Atmajaya Jakarta',
                'alamat' => 'Jl. Jenderal Sudirman No. 51, Jakarta',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'telepon' => '021-5703306',
                'email' => 'info@atmajaya.ac.id',
                'website' => 'https://www.atmajaya.ac.id',
            ],
            [
                'kode_pt' => 'PTS005',
                'nama_kampus' => 'Universitas Pelita Harapan',
                'alamat' => 'Jl. MH Thamrin Boulevard, Tangerang',
                'kota' => 'Tangerang',
                'provinsi' => 'Banten',
                'telepon' => '021-5460901',
                'email' => 'info@uph.edu',
                'website' => 'https://www.uph.edu',
            ],
            [
                'kode_pt' => 'PTS006',
                'nama_kampus' => 'Universitas Kristen Petra',
                'alamat' => 'Jl. Siwalankerto No. 121-131, Surabaya',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'telepon' => '031-2983455',
                'email' => 'info@petra.ac.id',
                'website' => 'https://www.petra.ac.id',
            ],
            [
                'kode_pt' => 'PTS007',
                'nama_kampus' => 'Universitas Muhammadiyah Malang',
                'alamat' => 'Jl. Raya Tlogomas No. 246, Malang',
                'kota' => 'Malang',
                'provinsi' => 'Jawa Timur',
                'telepon' => '0341-464318',
                'email' => 'info@umm.ac.id',
                'website' => 'https://www.umm.ac.id',
            ],
            [
                'kode_pt' => 'PTS008',
                'nama_kampus' => 'Universitas Islam Indonesia',
                'alamat' => 'Jl. Kaliurang KM 14.5, Yogyakarta',
                'kota' => 'Yogyakarta',
                'provinsi' => 'D.I. Yogyakarta',
                'telepon' => '0274-898444',
                'email' => 'info@uii.ac.id',
                'website' => 'https://www.uii.ac.id',
            ],
            [
                'kode_pt' => 'PTS009',
                'nama_kampus' => 'Universitas Sanata Dharma',
                'alamat' => 'Jl. Affandi, Yogyakarta',
                'kota' => 'Yogyakarta',
                'provinsi' => 'D.I. Yogyakarta',
                'telepon' => '0274-513301',
                'email' => 'info@usd.ac.id',
                'website' => 'https://www.usd.ac.id',
            ],
            [
                'kode_pt' => 'PTS010',
                'nama_kampus' => 'Universitas Dian Nuswantoro',
                'alamat' => 'Jl. Nakula I No. 5-11, Semarang',
                'kota' => 'Semarang',
                'provinsi' => 'Jawa Tengah',
                'telepon' => '024-3517261',
                'email' => 'info@dinus.ac.id',
                'website' => 'https://www.dinus.ac.id',
            ],
            // Additional Universities to reach 50+
            [
                'kode_pt' => 'REG001',
                'nama_kampus' => 'Universitas Negeri Medan',
                'alamat' => 'Jl. Willem Iskandar Pasar V, Medan',
                'kota' => 'Medan',
                'provinsi' => 'Sumatera Utara',
                'telepon' => '061-6613365',
                'email' => 'info@unimed.ac.id',
                'website' => 'https://www.unimed.ac.id',
            ],
            [
                'kode_pt' => 'REG002',
                'nama_kampus' => 'Universitas Negeri Padang',
                'alamat' => 'Jl. Prof. Dr. Hamka, Padang',
                'kota' => 'Padang',
                'provinsi' => 'Sumatera Barat',
                'telepon' => '0751-7053929',
                'email' => 'info@unp.ac.id',
                'website' => 'https://www.unp.ac.id',
            ],
            [
                'kode_pt' => 'REG003',
                'nama_kampus' => 'Universitas Negeri Jakarta',
                'alamat' => 'Jl. Rawamangun Muka, Jakarta',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'telepon' => '021-4893854',
                'email' => 'info@unj.ac.id',
                'website' => 'https://www.unj.ac.id',
            ],
            [
                'kode_pt' => 'REG004',
                'nama_kampus' => 'Universitas Negeri Malang',
                'alamat' => 'Jl. Semarang No. 5, Malang',
                'kota' => 'Malang',
                'provinsi' => 'Jawa Timur',
                'telepon' => '0341-551312',
                'email' => 'info@um.ac.id',
                'website' => 'https://www.um.ac.id',
            ],
            [
                'kode_pt' => 'REG005',
                'nama_kampus' => 'Universitas Negeri Semarang',
                'alamat' => 'Jl. Kelud Utara III, Semarang',
                'kota' => 'Semarang',
                'provinsi' => 'Jawa Tengah',
                'telepon' => '024-8508033',
                'email' => 'info@unnes.ac.id',
                'website' => 'https://www.unnes.ac.id',
            ],
            [
                'kode_pt' => 'REG006',
                'nama_kampus' => 'Universitas Negeri Surabaya',
                'alamat' => 'Jl. Ketintang, Surabaya',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'telepon' => '031-8296427',
                'email' => 'info@unesa.ac.id',
                'website' => 'https://www.unesa.ac.id',
            ],
            [
                'kode_pt' => 'REG007',
                'nama_kampus' => 'Universitas Negeri Makassar',
                'alamat' => 'Jl. Mallengkeri Raya, Makassar',
                'kota' => 'Makassar',
                'provinsi' => 'Sulawesi Selatan',
                'telepon' => '0411-884457',
                'email' => 'info@unm.ac.id',
                'website' => 'https://www.unm.ac.id',
            ],
            [
                'kode_pt' => 'REG008',
                'nama_kampus' => 'Universitas Tanjungpura',
                'alamat' => 'Jl. Prof. Dr. H. Hadari Nawawi, Pontianak',
                'kota' => 'Pontianak',
                'provinsi' => 'Kalimantan Barat',
                'telepon' => '0561-585342',
                'email' => 'info@untan.ac.id',
                'website' => 'https://www.untan.ac.id',
            ],
            [
                'kode_pt' => 'REG009',
                'nama_kampus' => 'Universitas Mulawarman',
                'alamat' => 'Jl. Kuaro, Samarinda',
                'kota' => 'Samarinda',
                'provinsi' => 'Kalimantan Timur',
                'telepon' => '0541-749343',
                'email' => 'info@unmul.ac.id',
                'website' => 'https://www.unmul.ac.id',
            ],
            [
                'kode_pt' => 'REG010',
                'nama_kampus' => 'Universitas Lambung Mangkurat',
                'alamat' => 'Jl. Brigjen H. Hasan Basry, Banjarmasin',
                'kota' => 'Banjarmasin',
                'provinsi' => 'Kalimantan Selatan',
                'telepon' => '0511-3304177',
                'email' => 'info@unlam.ac.id',
                'website' => 'https://www.unlam.ac.id',
            ],
            [
                'kode_pt' => 'REG011',
                'nama_kampus' => 'Universitas Sam Ratulangi',
                'alamat' => 'Jl. Kampus Unsrat, Manado',
                'kota' => 'Manado',
                'provinsi' => 'Sulawesi Utara',
                'telepon' => '0431-863886',
                'email' => 'info@unsrat.ac.id',
                'website' => 'https://www.unsrat.ac.id',
            ],
            [
                'kode_pt' => 'REG012',
                'nama_kampus' => 'Universitas Tadulako',
                'alamat' => 'Jl. Soekarno-Hatta KM 9, Palu',
                'kota' => 'Palu',
                'provinsi' => 'Sulawesi Tengah',
                'telepon' => '0451-422611',
                'email' => 'info@untad.ac.id',
                'website' => 'https://www.untad.ac.id',
            ],
            [
                'kode_pt' => 'REG013',
                'nama_kampus' => 'Universitas Halu Oleo',
                'alamat' => 'Jl. H.E.A. Mokodompit, Kendari',
                'kota' => 'Kendari',
                'provinsi' => 'Sulawesi Tenggara',
                'telepon' => '0401-390006',
                'email' => 'info@uho.ac.id',
                'website' => 'https://www.uho.ac.id',
            ],
            [
                'kode_pt' => 'REG014',
                'nama_kampus' => 'Universitas Pattimura',
                'alamat' => 'Jl. Ir. M. Putuhena, Ambon',
                'kota' => 'Ambon',
                'provinsi' => 'Maluku',
                'telepon' => '0911-322626',
                'email' => 'info@unpatti.ac.id',
                'website' => 'https://www.unpatti.ac.id',
            ],
            [
                'kode_pt' => 'REG015',
                'nama_kampus' => 'Universitas Cenderawasih',
                'alamat' => 'Jl. Kamp. Wolker, Jayapura',
                'kota' => 'Jayapura',
                'provinsi' => 'Papua',
                'telepon' => '0967-572115',
                'email' => 'info@uncen.ac.id',
                'website' => 'https://www.uncen.ac.id',
            ],
            [
                'kode_pt' => 'REG016',
                'nama_kampus' => 'Universitas Mataram',
                'alamat' => 'Jl. Majapahit No. 62, Mataram',
                'kota' => 'Mataram',
                'provinsi' => 'Nusa Tenggara Barat',
                'telepon' => '0370-633007',
                'email' => 'info@unram.ac.id',
                'website' => 'https://www.unram.ac.id',
            ],
            [
                'kode_pt' => 'REG017',
                'nama_kampus' => 'Universitas Nusa Cendana',
                'alamat' => 'Jl. Adisucipto, Kupang',
                'kota' => 'Kupang',
                'provinsi' => 'Nusa Tenggara Timur',
                'telepon' => '0380-881580',
                'email' => 'info@undana.ac.id',
                'website' => 'https://www.undana.ac.id',
            ],
            [
                'kode_pt' => 'REG018',
                'nama_kampus' => 'Universitas Gorontalo',
                'alamat' => 'Jl. Jenderal Sudirman No. 6, Gorontalo',
                'kota' => 'Gorontalo',
                'provinsi' => 'Gorontalo',
                'telepon' => '0435-827123',
                'email' => 'info@ung.ac.id',
                'website' => 'https://www.ung.ac.id',
            ],
            [
                'kode_pt' => 'REG019',
                'nama_kampus' => 'Universitas Sultan Ageng Tirtayasa',
                'alamat' => 'Jl. Raya Jakarta KM 4, Serang',
                'kota' => 'Serang',
                'provinsi' => 'Banten',
                'telepon' => '0254-280330',
                'email' => 'info@untirta.ac.id',
                'website' => 'https://www.untirta.ac.id',
            ],
            [
                'kode_pt' => 'REG020',
                'nama_kampus' => 'Universitas Bangka Belitung',
                'alamat' => 'Jl. Kampus Terpadu UBB, Bangka',
                'kota' => 'Bangka',
                'provinsi' => 'Kepulauan Bangka Belitung',
                'telepon' => '0717-422145',
                'email' => 'info@ubb.ac.id',
                'website' => 'https://www.ubb.ac.id',
            ],
        ];

        foreach ($kampuses as $kampus) {
            Kampus::create($kampus);
        }

        $this->command->info('✅ Created ' . count($kampuses) . ' universities successfully!');
    }
}
